version: "3.9"

services:
  metabase:
    container_name: metabase
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/x86_64
    volumes:
      - "/dev/urandom:/dev/random:ro"
      - "./metabase-data:/metabase-data"
      - "./plugins/duckdb.metabase-driver.jar:/plugins/duckdb.metabase-driver.jar"
    ports:
      - "${MB_PORT:-6120}:3000"
    environment:
      - MB_PLUGINS_DIR=/plugins
      - MB_DB_TYPE=duckdb
      - MB_DB_DBNAME=metabase
      - MB_DB_FILE=/metabase-data/duckdb_database.duckdb
      - MB_LOAD_SAMPLE_CONTENT=false
    healthcheck:
      test: "curl --fail -I http://127.0.0.1:3000/api/health || exit 1"
      interval: 5s
      timeout: 20s
      retries: 10

  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:24.8-alpine
    platform: linux/x86_64
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    secrets:
      - ${CLICKHOUSE_USER}
      - ${CLICKHOUSE_PASSWORD}
