version: "3.9"
services:
  metabase:
    container_name: metabase
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/x86_64
    volumes:
      # Provide randomness for Java
      - "/dev/urandom:/dev/random:ro"
      # Persist Metabase internal data (H2 database file)
      - "./metabase-data:/metabase-data"
      # Inject the DuckDB driver JAR into the plugins directory
      - "./plugins/duckdb.metabase-driver.jar:/plugins/duckdb.metabase-driver.jar"
    ports:
      - "${MB_PORT:-6120}:3000"
    environment:
      # Set the plugins directory to where the DuckDB driver is injected
      MB_PLUGINS_DIR: /plugins
      # Use H2 (a supported internal DB) for Metabase’s metadata
      MB_DB_TYPE: h2
      MB_DB_DBNAME: metabase
      MB_DB_FILE: /metabase-data/metabase.mv.db
      MB_LOAD_SAMPLE_CONTENT: "false"
    healthcheck:
      test: "curl --fail -I http://127.0.0.1:3000/api/health || exit 1"
      interval: 5s
      timeout: 20s
      retries: 10

  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:24.8-alpine
    platform: linux/x86_64
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    # ClickHouse is available only within the Docker network (no published ports)