version: "3.9"
services:
  metabase_app:
    container_name: metabase_app
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Persist Metabase internal data (the DuckDB file will be stored here)
      - ./metabase-data:/metabase-data
      # Inject the DuckDB driver JAR from your host into the container's plugins directory
      - ./plugins/duckdb.metabase-driver.jar:/plugins/duckdb.metabase-driver.jar
    restart: unless-stopped
    ports:
      - "${MB_PORT:-6120}:3000"
    environment:
      # Points Metabase to the plugins directory
      MB_PLUGINS_DIR: /plugins
      # Configure Metabase to use DuckDB as the embedded application database
      MB_DB_TYPE: duckdb
      MB_DB_DBNAME: metabase
      # Path to the DuckDB file (persisted via the mounted volume)
      MB_DB_FILE: /metabase-data/duckdb_database.duckdb
      # Do not load sample content on startup
      MB_LOAD_SAMPLE_CONTENT: "false"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:24.8-alpine
    platform: linux/x86_64
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    # No port mappings here; ClickHouse remains accessible only within the Docker network.